name: Context Demo

on:
  workflow_dispatch:

jobs:
  show-context:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: echo "${{ toJSON(github) }}"

      - name: Print Job context
        run: echo "${{ toJSON(job) }}"
